version: 2
updates:
  # >>> template:base
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore
      include: scope
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore
      include: scope
    groups:
      pre-commit-hooks:
        patterns: ["*"]

  - package-ecosystem: uv
    directory: /.devtools
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore
      include: scope
    groups:
      devtools:
        patterns: ["*"]
  # <<< template:base
